name: UHCRandom
main: net.samagames.uhcrandom.UHCRandom
version: 1.0

depend: [SamaGamesAPI, SurvivalAPI]

load: STARTUP

author: Rigner
website: http://samagames.net/

commands:
    modules:
        usage:
        description: Displays current modules
        aliases: [module]
    enablemodule:
        usage:
        description: